version: "3.8"

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: analytics-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: government-analytics

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: analytics-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Ollama AI Service
  ollama:
    image: ollama/ollama:latest
    container_name: analytics-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
    # Uncomment the following lines if you have NVIDIA GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # Government Analytics Backend
  backend:
    build: ./server
    container_name: analytics-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
      - ollama
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/government-analytics
      - REDIS_URL=redis://redis:6379
      - OLLAMA_URL=http://ollama:11434
      - LOCAL_AI_ENABLED=true
      - DOCKER_ENV=true
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      - ./uploads:/app/uploads
      - ./models:/app/models

volumes:
  mongodb_data:
  redis_data:
  ollama_data:
